name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: Configure CMake
          # Use a bash shell so we can use the same syntax for environment variable
          # access regardless of the host operating system
          shell: bash
          working-directory: ${{github.workspace}}/build

          run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

        - name: Build
          working-directory: ${{github.workspace}}/build
          shell: bash
          run: cmake --build . --config $BUILD_TYPE
        

        - name: Building
          shell: bash
          run: |
            mkdir build
            cd build
            cmake ..
            make

        - name: Unit Valgrind Testing
          run: |
           cd tests
           valgrind --tool=memcheck --leak-check=yes ./testlib
           
